### ISSUE TITLE
Thanks and Is it dead?

### ISSUE THREAD

**Issue by codeyash** [Andersbakken/LazyTextEdit#1]
Its very nice project. I'm very much interested in it.

I'm author of KineticWing IDE. This component will bring large file support. 

Let me know if you have any interest in it.

**Comment by Andersbakken** [comment]
Hi

That's funny. I had completely forgotten about it. I haven't done any work
on it for years but feel free to take it and do whatever you want with it.
I'm frankly not really using Qt anymore so I wouldn't even know how to
start maintaining it again. I would happily transfer ownership of the
project to you if you're interested.

Anders

**Comment by codeyash** [comment]
I'm very much very. The problem is I've lots of tasks of my product. And this component needs big update. I mean now we are using Qt 5.4 

If possible I would like to have little chat with you regarding few basic Qs like what exactly and how much you changed from normal Qt internal APIs and can you support bit me for this one If I take new maintainer position.

Thanks,
Yash

**Comment by Andersbakken** [comment]
Sure. I may or may not remember all the decisions etc but feel free to
shoot me some questions.

Anders

**Comment by codeyash** [comment]
I've sent a private mail. Thanks.
